### ISSUE TITLE
Dockerfile missing git

### ISSUE THREAD

**Issue by synergiator** [fic2/dockerfiles#1]
Base image apparently does not have git installed. Please add it to the Dockerfile. 

We have executed the Dockerfile and got this error 

Step 3 : RUN git clone https://github.com/fraunhoferfokus/ocdb /root/ocdb
 ---> Running in ca048785e383
[91m/bin/sh: 1: [0m[91mgit: not found[0m[91m
[0m2015/02/03 11:53:27 The command [/bin/sh -c git clone https://github.com/fraunhoferfokus/ocdb /root/ocdb] returned a non-zero code: 127

**Comment by cgeoffroy** [comment]
The git package was removed from the used base image: https://github.com/joyent/docker-node/tree/master/0.10/slim in the commit joyent/docker-node@01fe973d3a61a13efda3e5775a191525491ca64b .

The commit 516d149c24e905b6db50f6ce4909014ea510dd0d adds it back.
