### ISSUE TITLE
Please add some idle time to let the service launch

### ISSUE THREAD

**Issue by synergiator** [fic2/dockerfiles#2]
Hi,

please add some idle time to ensure that the service has time to launch.
Use sth. like:

echo -n "Waiting service to launch"
while ! (netcat -vz localhost 12345 &> /dev/null); do echo -n "."; sleep 5; done
echo ""
echo "service is running."

Otherwise the test.sh will think there is no service at all.

Current build log:
- docker run -d -p 62049:59125 fic2/fatts:latest
  15e604f8c61214bb5d6d29c8e28e63260ff39da737282f0e3cb75d832b608103
- cd fatts
- chmod u+x test.sh
- ./test.sh localhost 62049
  Entering FA-TTS SE smoke test sequence. FA-TTS SE validation procedure engaged. Target host: localhost, port: 62049
  Run smoke test for /info/version
  Curl command for /info/version failed. Validation procedure terminated.
  Debug information: HTTP code 000 instead of expected 200 from localhost:62049

**Comment by dirkk0** [comment]
Did so, didn't work.
